# Site settings
title: Spencer Norwick - Engineering Porfolio
description: A place for me to share what I've been working on.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spencer Norwick
user_description: Mechanical engineer interested in Robotics...
user_title: Mechanical Engineer
email: norwick2@illinois.edu
twitter_username: lorem_ipsum
github_username:  spencer-norwick
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
